name: Update from Google Doc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Update index.html from Google Doc
        run: python update_index.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add index.html
          git commit -m "Auto-update from Google Doc" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

